export type {
  AssignmentState,
  ComposerMode,
  ConversationDetail,
  ConversationRow,
  ConversationStatus,
  ConversationTimelineItem,
  OccupantSummary,
  HelpdeskAssigneeOption,
  HelpdeskDashboardMetrics,
  HelpdeskInboxMetric,
  HelpdeskRecentActivityItem,
  HelpdeskStatusCount,
  InboxChannelKey,
  InboxSectionKey,
  InboxViewDefinition,
  InboxViewKey,
  PriorityLevel,
  SlaState,
  SuggestionItem,
  TicketSummary,
  TimelineItemType,
} from "../../../../shared/helpdesk";

export { DEFAULT_INBOX_VIEW_KEY, inboxChannelKeys, inboxViewKeys } from "../../../../shared/helpdesk";
