export type {
  AssignmentState,
  ComposerMode,
  ConversationDetail,
  ConversationRow,
  ConversationStatus,
  ConversationTimelineItem,
  CustomerSummary,
  HelpdeskAssigneeOption,
  HelpdeskDashboardMetrics,
  HelpdeskInboxMetric,
  HelpdeskRecentActivityItem,
  HelpdeskStatusCount,
  InboxFilterState,
  InboxScaffoldData,
  InboxSectionKey,
  InboxViewDefinition,
  InboxViewKey,
  PriorityLevel,
  SlaState,
  SuggestionItem,
  TicketSummary,
  TimelineItemType,
} from "../../../../shared/helpdesk";

export { DEFAULT_INBOX_VIEW_KEY, inboxViewKeys } from "../../../../shared/helpdesk";
